---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- value: A) Una elevada inflación esperada puede contraer la curva de la demanda agregada.
  checked: false
- value: B) Tiene pendiente negativa por el efecto de los saldos reales.
  checked: false
- value: C) No generan ningún impacto sobre la inflación, la producción o el desempleo.
  checked: false
- value: D) Depende de las políticas económicas del gobierno (fiscales, monetarias
    y cambiarias).
  checked: false
- value: E) Más de una es correcta.
  checked: true
