---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- value: A) El aumento de los precios genera un aumento en la demanda de saldos monetarios.
  checked: false
- value: B) Al aumentar la tasa de interés (i) se incrementa el costo de oportunidad
    de mantener dinero líquido y por lo cual se incrementa la demanda de saldos reales.
  checked: false
- value: C) El aumento de la producción o ingreso real eleva el número de transacciones
    por lo que se eleva la demanda de dinero como medio de cambio.
  checked: false
- value: D) Las innovaciones financieras (uso de tarjetas de crédito, cajeros automáticos,
    etc) elevan la velocidad de circulación del dinero y, con ello, también de la
    demanda de dinero.
  checked: false
- value: E) Más de una es correcta.
  checked: true
