---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:BSON::Document
  value: A) Cuanto mayor es la sensibilidad de la inversión a la tasa de interés,
    más vertical es la curva IS.
  checked: false
- !ruby/hash:BSON::Document
  value: B) Una menor propensión marginal a consumir hará que la curva IS sea más
    horizontal.
  checked: false
- !ruby/hash:BSON::Document
  value: C) Un aumento de la tasa impositiva (t) provocará que la IS sea más empinada.
  checked: true
- !ruby/hash:BSON::Document
  value: D) Es afectada por las políticas monetarias.
  checked: false
- !ruby/hash:BSON::Document
  value: E) Una expansión fiscal siempre generará Crowding Out debido a la caída del
    gasto privado.
  checked: false
